name: bloc_get_it
description: "Bloc state management with get_it for DI instead of provider"
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
